Alerting tests
elastic/elastic-stack-testing pull request #1076
Opened 2021-11-16 16:19 UTC by chrisronline

2022-01-18 16:57 UTC, chrisronline commented
@liza-mae Can this be merged?

2022-01-18 20:21 UTC, EricDavisX requested changes

2022-01-18 20:21 UTC, EricDavisX commented on ci/upgrade/tests/build.gradle
> +task deployment716 {
since mid November time frame I think the 7.17 release has superseded 7.16 as the 7.last build, we'll need to adjust and add in one more scenario and adjust the existing, right?

2022-01-18 20:22 UTC, EricDavisX commented
Hi - I'm just getting up to speed with the new ResponseOps team, who I suppose should own these tests (and the ML/MLR QA team can help).  Does anything need to change from mid-November to reflect that in the code / codeowner citation so the right team is notified when things need attention.

2022-01-18 20:23 UTC, EricDavisX commented
@XavierM and @mikecote FYI on the wip nearly merging in.  @elastic/ml-qa you too.

2022-01-19 00:10 UTC, liza-mae commented on ci/upgrade/tests/build.gradle
> +task deployment711 {
Task ```deployment``` was renamed to ```deployment711```, so you will need to add back a task called ```deployment```, as it breaks the other tasks that depend on it, you can keep the other ```deployment*``` tasks. 

```
task deployment {
    doFirst {
        ext.esBaseUrl = ""
        ext.kbnBaseUrl = ""
        ext.username = ""
        ext.version = ""
        ext.upgradeVersion = ""
        ext.password = ""
    }
}
```

2022-01-19 00:10 UTC, liza-mae requested changes
LGTM, just one change required.

2022-01-19 00:12 UTC, liza-mae commented on ci/upgrade/tests/build.gradle
> +task deployment716 {
This file is used for testing data imports into the different versions, it is expected we would still have 7.16 in the upgrade path testing.  You can add another version ex: 7.17 if the API is different  from the ones already listed.

2022-03-10 16:34 UTC, EricDavisX commented
@liza-mae how do we get notified (in Response Ops) if / when the test were to fail?  The team may still want this, it's good to have coverage.  I'm not very confident on pushing changes myself - @chrisronline do you know the estf system well?  if we change 'task deployment711' back to 'deployment', can we just update the subsequent usage of that [here](https://github.com/elastic/elastic-stack-testing/pull/1076/files#diff-9a59fa2f25634894dcbe5d480694a5ec13ee583e61e3b36e193a12110182e3c5R22) and call it done?

2022-03-11 01:17 UTC, liza-mae commented
@EricDavisX yes make the change requested in this review.  It looks like the tests also need to be added, which is PR: https://github.com/elastic/kibana/pull/118890 - again these have been open for awhile, so maybe best if @chrisronline can get this one and the one in kibana repo up to date and merged.  

Once those PRs are in, I will add it to our CI.  Right now I create issues when tests fails and those will be routed to your team to investigate.

2022-03-15 13:59 UTC, EricDavisX commented
we'll make time for this in the 8.3 cycle, coming soon.

2022-06-13 16:33 UTC, XavierM commented
> we'll make time for this in the 8.3 cycle, coming soon.

what about 8.4 cycle?

2022-06-27 16:42 UTC, EricDavisX commented
I've discussed with the RAM team and MLR-QA Team and I'm not sure we want to invest in 2 separate upgrade test repos now.  The MLR-QA Team is using the machine-learning-qa framework for upgrade tests for all of Rules, Alerts, Cases and Connectors.  So we're closing this out.  We can always re-open later.

2022-06-27 16:42 UTC, closed without merging