Remove non-existent tests and temporarily remove session idle timeout tests from the Cloud test suite.
elastic/elastic-stack-testing pull request #785
Opened 2021-01-27 16:24 UTC by azasypkin

Notable changes:

* Removing references to the non-existent test suites that were moved to a single location instead (`x-pack./tests/security_api_integration`);
* Removing `xpack.encryptedSavedObjects.*` and `xpack.security.*` Kibana config overrides for the Cloud environment since Cloud makes sure these are always set.
* Temporarily disabling Session Idle Timeout tests from the Cloud test suite since they require custom Kibana config and test plugin that we don't support yet.

2021-01-27 16:25 UTC, azasypkin commented on .gitignore
> +.idea/
__note:__ I see we account for IntelliJ IDEs in most of our repositories, so I thought it'd be nice to have it here as well.

2021-01-27 16:26 UTC, azasypkin commented on ci/cloud/product/settings/kibana.yml
> -xpack.encryptedSavedObjects.encryptionKey: "DkdXazszSCYexXqz4YktBGHCRkV6hyNK"
__note:__ Cloud always sets these values so we don't have to. Cloud also uses 72h idle timeout that should work well for tests as well.

2021-01-27 16:36 UTC, azasypkin commented on ci/kibana/group_defs.sh
>                security_api_integration
__note:__ `security_api_integration` includes all security app integration tests, that's probably why it takes about `2 hr 57 min` to complete the `xpackExtGrp4` job right now while `xpackExtGrp2` job requires only `1 hr 6 min`. So I tried to re-balance this a bit, but let me know if there is a better way to do that.

2021-01-27 16:37 UTC, azasypkin commented
@liza-mae would mind taking a look at this PR whenever you have time? Thanks!

2021-01-27 18:46 UTC, liza-mae commented on ci/cloud/product/settings/kibana.yml
> -xpack.encryptedSavedObjects.encryptionKey: "DkdXazszSCYexXqz4YktBGHCRkV6hyNK"
I don't understand what you mean about non-ESS test suites, these settings are only for ESS.  Do you mean will it break other test suites that are run on ESS yes most likely unless those suites have removed these settings.  We need to find out before we accept this change.

2021-01-27 18:53 UTC, liza-mae commented on ci/kibana/group_defs.sh
>                security_api_integration
I can't accept this change until I know the impact of the re-balance, no detailed breakdown was given other than a time for group.   Looks like you also removed some things?  I prefer we split a re-balancing, if needed, into a separate PR and focus this PR on removing coverage of what you feel is not applicable for security on ESS, which is what I thought the scope of this PR was.

2021-01-27 18:55 UTC, liza-mae requested changes
Please make this PR specific to removing or isolating tests for the security feature. 
If we need to re-balance CI jobs for time - we can create another PR that focuses on that but I would need a detailed breakdown as to why.

2021-01-27 19:17 UTC, azasypkin commented on ci/cloud/product/settings/kibana.yml
> -xpack.encryptedSavedObjects.encryptionKey: "DkdXazszSCYexXqz4YktBGHCRkV6hyNK"
>  don't understand what you mean about non-ESS test suites, these settings are only for ESS.

I mean I see `estf-ece-kibana-tests` and `estf-eck-kibana-tests` test suites on CI. Generally speakings these may be treated as Cloud, but they aren't ESS. Hence my question is in which environments except for ESS we use this Kibana config?

> Do you mean will it break other test suites that are run on ESS yes most likely unless those suites have removed these settings. 

Hmm, why any other tests will break if they run in ESS where these settings are always set by the Cloud infrastructure itself? I'm not sure I'm following, would you mind elaborating a bit?

2021-01-27 19:21 UTC, azasypkin commented on ci/kibana/group_defs.sh
>                security_api_integration
> I can't accept this change until I know the impact of the re-balance, no detailed breakdown was given other than a time for group.

Sorry, I was just not sure how to get this info here. I know how to get this info in Kibana's CI since PR changes are immediately tested on CI, but what is the workflow for re-balancing of `estf-cloud-kibana-tests`?

>  I prefer we split a re-balancing, 

Sure, I'll revert re-balancing and keep only removal of the non-existent jobs.

2021-01-27 19:24 UTC, azasypkin commented on ci/cloud/product/settings/kibana.yml
> -xpack.encryptedSavedObjects.encryptionKey: "DkdXazszSCYexXqz4YktBGHCRkV6hyNK"
The motivation behind this change is that we definitely don't want to override any of the Cloud defaults unless we have a strong reason to do that, and I don't see that reason unless we re-use this config for tests in non-ESS environment.

2021-01-27 19:35 UTC, liza-mae commented on ci/cloud/product/settings/kibana.yml
> -xpack.encryptedSavedObjects.encryptionKey: "DkdXazszSCYexXqz4YktBGHCRkV6hyNK"
I understand then I will accept this change.  I agree with you if they are already set we should not be overriding them.  As far as non-ESS yes those might break but not an issue, I can create separate settings for ECE and ECK after investigating the defaults for those platforms.

2021-01-27 19:36 UTC, liza-mae commented on ci/kibana/group_defs.sh
>                security_api_integration
Yes thank you - this repo is not set up to do PRs.

2021-01-28 08:21 UTC, azasypkin commented on ci/kibana/jenkins_kibana_tests.sh
> -                     test/security_api_integration/session_idle.config.ts
__note:__ as we agreed, I'm temporarily excluding this tests from the Cloud run until we can figure out how to use custom config.

2021-01-28 08:22 UTC, azasypkin commented
> Please make this PR specific to removing or isolating tests for the security feature.

Thanks for the feedback, PR should be ready for the second pass.

2021-01-28 16:39 UTC, liza-mae approved these changes
LGTM

2021-01-28 16:55 UTC, merged