Security Solution Upgrade testing Phase 1: Prepare the data that we are going to use for testing
elastic/elastic-stack-testing pull request #929
Opened 2021-07-06 07:18 UTC by MadameSheema

Following the issue: https://github.com/elastic/elastic-stack-testing/issues/928 we are preparing the test data we are going to need to perform the testing.

The idea is first to create a custom query detection rule, and then, generate an alert for it.

In order to do that, we are creating a new `UploadSecuritySolutionData.java`. Here we are first creating a siem signals index for the default workspace. This is because, in order to be able to create a rule, we need that index to exist in the workspace where the rule is going to be created. Once the index is created, we create a custom query detection rule and then we create a document that matches with the rule index and query to generate the alert.

As part of this PR, we are also creating the `upload_security_solution_data` task that executes the above.

2021-07-06 07:20 UTC, MadameSheema commented
@liza-mae cam you please take a look at this PR? Thanks :)

2021-07-06 07:21 UTC, MadameSheema commented on ci/upgrade/buildSrc/src/main/java/org/estf/gradle/UploadSecuritySolutionData.java
> +            String jsonstr = "{\"rule_id\": \"123\" , \"risk_score\": 7, \"description\": \"My description\", \"interval\": \"10s\", \"name\": \"Rule Name\", \"severity\": \"low\", \"type\": \"query\
@liza-mae I'm not quite happy with this solution. Is there any easy way to have this json on a separate file? Thanks :)

2021-07-06 18:41 UTC, liza-mae commented on ci/upgrade/buildSrc/src/main/java/org/estf/gradle/UploadSecuritySolutionData.java
> +            String jsonstr = "{\"rule_id\": \"123\" , \"risk_score\": 7, \"description\": \"My description\", \"interval\": \"10s\", \"name\": \"Rule Name\", \"severity\": \"low\", \"type\": \"query\
@MadameSheema yes you can use a separate file.  You can place json files in ```ci/upgrade/buildSrc/src/main/resources```.  There is an example in:   
https://github.com/elastic/elastic-stack-testing/blob/7a11b7b943ae81d2c85b4a558d027070a1886d1f/ci/upgrade/buildSrc/src/main/java/org/estf/gradle/UpgradeAssistantApi.java#L211

2021-07-06 18:42 UTC, liza-mae commented on ci/upgrade/ess/build.gradle
> +import org.estf.gradle.UploadDataSecuritySolution
This should be: ```import org.estf.gradle.UploadSecuritySolutionData```

2021-07-06 18:43 UTC, liza-mae commented on ci/upgrade/ess/build.gradle
> +        tasks.create("upload_security_solution_data" + i, UploadDataSecuritySolution) {
This should be: ```tasks.create("upload_security_solution_data" + i, UploadSecuritySolutionData) {```

2021-07-06 18:43 UTC, liza-mae commented on ci/upgrade/ess/build.gradle
> +        tasks.findByName("upload_security_solution_data" + i).mustRunFater("upload_data" + i)
This should be: ```tasks.findByName("upload_security_solution_data" + i).mustRunAfter("upload_data" + i)```

2021-07-06 18:46 UTC, liza-mae commented on ci/upgrade/buildSrc/src/main/java/org/estf/gradle/UploadSecuritySolutionData.java
> +
It appears that this data is not applicable to versions 5.x and 6.x, so let's only run them on 7.x or greater.

Please add the following input 
``` 
@Input 
public String version;

@Input
public String upgradeVersion;
```

2021-07-06 18:48 UTC, liza-mae commented on ci/upgrade/buildSrc/src/main/java/org/estf/gradle/UploadSecuritySolutionData.java
> +    public void run() throws IOException, InterruptedException {
It appears that this data is not applicable to versions 5.x and 6.x, so let's only run them on 7.x or greater.

Please replace with the following version check: 
``` 
    RestApi api = new RestApi(username, password, version, upgradeVersion);
    int majorVersion = api.setMajorVersion();
    if (majorVersion > 6) {
        createsSiemSignalsIndex();
        createsDetectionRule();
        createsDocumentIndex();
        createsDocumentToGenerateAlert();
}

2021-07-06 18:50 UTC, liza-mae commented on ci/upgrade/ess/build.gradle
> +                password = rootProject.props.es_password
It appears that this data is not applicable to versions 5.x and 6.x, so let's only run them on 7.x or greater.
Please add the following options to your task: 
```
  version = originating_version
  upgradeVersion = upgrade_version
```

2021-07-06 18:53 UTC, liza-mae requested changes
Looks great, just a few changes requested.

2021-07-06 20:46 UTC, MadameSheema commented on ci/upgrade/ess/build.gradle
> +import org.estf.gradle.UploadDataSecuritySolution
True I did I typo here.

2021-07-07 14:32 UTC, MadameSheema commented
@liza-mae I  have updated the PR with the required changes, can you please take a look at it again when you have the chance? Thanks :)

2021-07-07 15:33 UTC, liza-mae commented on ci/upgrade/buildSrc/src/main/java/org/estf/gradle/UploadSecuritySolutionData.java
> +            String file = "buildSrc/src/main/resources/detectionRule.json"
Add missing ```;``` at the end of line

2021-07-07 15:33 UTC, liza-mae commented on ci/upgrade/buildSrc/src/main/java/org/estf/gradle/UploadSecuritySolutionData.java
> +            String jsonStr = new String(Files.readAllBytes(Paths.get(file)))
Add missing ```;``` at the end of line

2021-07-07 15:34 UTC, liza-mae requested changes
Looks good, just a couple lines are missing an ending colon.

2021-07-07 15:44 UTC, MadameSheema commented
Thanks for the review! Changes done @liza-mae

2021-07-07 16:44 UTC, liza-mae approved these changes
LGTM, thanks @MadameSheema

2021-07-07 18:03 UTC, merged